micronaut:
  application:
    name: kotlinGerenciadorTarefas

# Postgres
#datasources:
#  default:
#    url: ${JDBC_URL:`jdbc:postgresql://localhost:5433/gerenciador-tarefa`}
#    driverClassName: org.postgresql.Driver
#    username: ${JDBC_USER:postgres}
#    password: ${JDBC_PASSWORD:postgres}
#    schema-generate: CREATE_DROP
#    dialect: POSTGRES
#    connection-timeout: 2000

datasources:
  default:
    url: 'jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    driverClassName: org.h2.Driver
    username: sa
    password: ''


# JPA
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true

# Flyway
flyway:
  datasources:
    default:
      enabled: true
